commands = set([
   # Document Structure
    '\\documentclass',
    '\\usepackage',
    '\\title',
    '\\author',
    '\\date',
    '\\maketitle',
    '\\tableofcontents',
    '\\chapter',
    '\\section',
    '\\subsection',
    '\\subsubsection',
    '\\paragraph',
    '\\subparagraph',
    '\\appendix',
    '\\bibliography',
    '\\bibliographystyle',

    # Text Formatting
    '\\textbf',
    '\\textit',
    '\\texttt',
    '\\textsc',
    '\\underline',
    '\\emph',
    '\\dots',

    # Environments
    '\\begin',
    '\\end',
    '\\item',
    '\\itemize',
    '\\enumerate',
    '\\description',
    '\\flushleft',
    '\\flushright',
    '\\center',
    '\\quote',
    '\\quotation',
    '\\verbatim',
    '\\figure',
    '\\table',
    '\\tabular',
    '\\array',

    # Math Mode
    '$',
    '\\(',
    '\\)',
    '\\[',
    '\\]',
    '\\text',
    '\\frac',
    '\\sqrt',
    '\\sum',
    '\\int',
    '\\lim',
    '\\log',
    '\\sin',
    '\\cos',
    '\\tan',

    # Figures and Tables
    '\\includegraphics',
    '\\caption',
    '\\label',
    '\\ref',
    '\\footnote',

    # Cross-Referencing
    '\\label',
    '\\ref',

    # Misc
    '\\newline',
    '\\clearpage',
    '\\pagebreak',
    '\\today',
    '\\pagenumbering',
    '\\thispagestyle',
    '\\newpage',
    '\\input',
    '\\include',
    '\\footnote',
    '\\cite',
    '\\citep',
    '\\citet',
    '\\citeauthor',
    '\\citeyear',
    '\\url',
    
    '\\cdot',
    '\\times',
    '\\div',
    '\\pm',
    '\\mp',
    '\\leq',
    '\\geq',
    '\\neq',
    '\\approx',
    '\\equiv',
    '\\in',
    '\\notin',
    '\\subset',
    '\\supset',
    '\\subseteq',
    '\\supseteq',
    '\\cup',
    '\\cap',
    '\\setminus',
    '\\mathbb',
    '\\mathbf',
    '\\mathcal',
    '\\mathrm',
    '\\mathsf',
    '\\mathit',
    '\\mathnormal',
    '\\mathfrak',
    '\\hat',
    '\\bar',
    '\\tilde',
    '\\check',
    '\\vec',
    '\\overrightarrow',
    '\\overleftarrow',
    '\\underline',
    '\\widehat',
    '\\widetilde',
    '\\overline',
    '\\sqrt',
    '\\binom',
    '\\choose',

    # More Text Formatting
    '\\textsc',
    '\\textbf',
    '\\textit',
    '\\texttt',
    '\\textsf',
    '\\textup',
    '\\textsl',
    '\\uppercase',
    '\\lowercase',
    '\\tiny',
    '\\scriptsize',
    '\\footnotesize',
    '\\small',
    '\\normalsize',
    '\\large',
    '\\Large',
    '\\LARGE',
    '\\huge',
    '\\Huge',
    '\\emph',
    '\\uppercase',
    '\\lowercase',
    '\\raggedleft',
    '\\raggedright',
    '\\centering',
    '\\doublespacing',
    '\\singlespacing',
    '\\onehalfspacing',
    '\\fontsize',
    '\\linespread',
    '\\color',

    #Misc
    '\\multicolumn',
    '\\cmidrule'
])
